[build-system]
requires = [
    "setuptools>=61.0", 
    "wheel", 
    "Cython>=0.29.36", 
    "numpy>=1.24.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "beat-detection"
version = "0.1.0"
description = "Music beat detection and metronome overlay tool"
requires-python = ">=3.12"
authors = [
    {name = "Beat Detection Team"}
]
readme = "README.md"

dependencies = [
    "madmom @ git+https://github.com/CPJKU/madmom.git",
    #"librosa>=0.10.0",
    "soundfile>=0.12.1",
    "numpy>=1.24.0",
    "moviepy>=1.0.3",
    "pillow>=9.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "black>=23.7.0",
    "ruff>=0.0.285",
    "mypy>=1.5.1",
    "Cython>=0.29.36"
]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
line-length = 88
target-version = "py312"
select = ["E", "F", "I", "D"]
ignore = ["D100", "D104", "D107"]

[tool.ruff.lint]
select = ["E", "F", "I", "D"]
ignore = ["D100", "D104", "D107"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.setuptools]
packages = ["beat_detection", "beat_detection.core", "beat_detection.utils", "beat_detection.cli"]

[project.scripts]
detect-beats = "beat_detection.cli.detect_beats:main"
generate-videos = "beat_detection.cli.generate_videos:main"
