[build-system]
requires = [
    "setuptools>=61.0", 
    "wheel", 
    "Cython>=0.29.36", 
    "numpy>=1.24.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "beat-detection"
version = "0.1.0"
description = "Music beat detection and metronome overlay tool"
requires-python = ">=3.12"
authors = [
    {name = "Beat Detection Team"}
]
readme = "README.md"

dependencies = [
    "madmom @ git+https://github.com/CPJKU/madmom.git",
    #"librosa>=0.10.0",
    "soundfile>=0.12.1",
    "numpy>=1.24.0",
    "moviepy>=1.0.3",
    "pillow>=9.0.0",
    "fastapi>=0.104.1",
    "uvicorn>=0.23.2",
    "python-multipart>=0.0.6",
    "jinja2>=3.1.2",
    "aiofiles>=23.2.1"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.1",
    "pytest-cov>=4.1.0",
    "httpx>=0.25.0",
    "black>=23.7.0",
    "ruff>=0.0.285",
    "mypy>=1.5.1",
    "Cython>=0.29.36"
]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff.lint]
# Enable specific rules
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "D",  # pydocstyle
]

# Disable specific rules
ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D107",  # Missing docstring in __init__
    "D203",  # 1 blank line required before class docstring
    "D213",  # Multi-line docstring summary should start at the second line
]

# Line length configuration
line-length = 88
target-version = "py312"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.setuptools]
packages = ["beat_detection", "beat_detection.core", "beat_detection.utils", "beat_detection.cli", "web_app"]

[project.scripts]
detect-beats = "beat_detection.cli.detect_beats:main"
generate-videos = "beat_detection.cli.generate_videos:main"
beat-webapp = "web_app.app:main"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["web_app/test_app.py"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-v --cov=web_app --cov-report=term-missing"

[dependency-groups]
dev = [
    "ruff>=0.9.10",
]
