name: Beat Detection App Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        pip install -U uv
        uv venv
        source .venv/bin/activate
        uv pip install ".[dev,beat_this_algo]"
        # Print installed packages to verify dependencies
        uv pip list
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Setup configuration files
      run: |
        # Copy example configuration files to their actual locations
        cp etc/config.json.example etc/config.json
        cp etc/users.json.example etc/users.json
        
        # List the configuration files to verify
        ls -la etc/
        
    - name: Run diagnostic checks
      run: |
        source .venv/bin/activate
        echo "=== Python version ==="
        python --version
        
        echo "=== List of installed packages ==="
        uv pip list
        
        echo "=== Dependency verification ==="
        echo "Checking core dependencies..."
        python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"
        python -c "import madmom; print(f'madmom version: {madmom.__version__}')"
        
        echo "Checking web app dependencies..."
        python -c "import fastapi; print(f'FastAPI version: {fastapi.__version__}')"
        python -c "import httpx; print(f'httpx version: {httpx.__version__}')" || echo "httpx is missing - needed for web app tests"
        
        echo "Checking beat detection dependencies..."
        python -c "import torch; print(f'PyTorch version: {torch.__version__}')" || echo "PyTorch is missing - needed for beat_this detector"
        if python -c "import beat_this" 2>/dev/null; then
          echo "beat_this module is available"
        else
          echo "beat_this module is missing - needed for beat_this detector tests"
        fi
        
        echo "=== Test paths verification ==="
        ls -la tests/
        ls -la beat_detection/core/ | grep test
       
    - name: Run tests
      run: |
        source .venv/bin/activate
        # Run all tests with more verbosity
        pytest -v --override-ini="addopts=" -xvs

    - name: Tag successful main branch builds
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        TAG_NAME="tests-passed-$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME 