name: Beat Detection App Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        pip install -U uv
        uv venv
        source .venv/bin/activate
        echo "======== Cleaning uv cache ========"
        uv cache clean
        echo "======== Installing NumPy and Cython explicitly (no cache) ========"
        uv pip install --no-cache numpy cython
        echo "======== Verifying NumPy and Cython installation ========"
        uv pip list | grep -E "numpy|Cython" || echo "NumPy or Cython not found after explicit install"
        echo "======== Installing project dependencies (with verbosity, no cache) ========"
        uv pip install --verbose --no-cache ".[dev]"
        # Print installed packages to verify dependencies
        echo "======== Listing all installed packages ========"
        uv pip list
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
       
    - name: Run tests
      run: |
        source .venv/bin/activate
        # Run all tests with more verbosity
        pytest -v --override-ini="addopts=" -xvs
