name: Beat Detection App Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        pip install -U uv
        uv venv
        source .venv/bin/activate
        uv pip install ".[dev,beat_this_algo]"
        # Print installed packages to verify dependencies
        uv pip list
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Setup configuration files
      run: |
        # Copy example configuration files to their actual locations
        cp etc/config.json.example etc/config.json
        cp etc/users.json.example etc/users.json
        
        # List the configuration files to verify
        ls -la etc/
        
    - name: Run diagnostic checks
      run: |
        source .venv/bin/activate
        echo "=== Python version ==="
        python --version
        
        echo "=== List of installed packages ==="
        uv pip list
        
        echo "=== Dependency verification ==="
        echo "Checking core dependencies..."
        python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"
        python -c "import madmom; print(f'madmom version: {madmom.__version__}')"
        
        echo "Checking web app dependencies..."
        python -c "import fastapi; print(f'FastAPI version: {fastapi.__version__}')"
        python -c "import httpx; print(f'httpx version: {httpx.__version__}')" || echo "httpx is missing - needed for web app tests"
        
        echo "Checking beat detection dependencies..."
        python -c "import torch; print(f'PyTorch version: {torch.__version__}')" || echo "PyTorch is missing - needed for beat_this detector"
        if python -c "import beat_this" 2>/dev/null; then
          echo "beat_this module is available"
          # Try to verify beat_this can be imported and contains expected components
          python -c "import beat_this; print(f'beat_this has the following attributes: {dir(beat_this)}')"
          python -c "from beat_this import BeatThis; print('BeatThis class is available')" || echo "BeatThis class not found in beat_this module"
        else
          echo "beat_this module is missing - needed for beat_this detector tests"
        fi
        
        echo "=== Test paths verification ==="
        ls -la tests/
        ls -la beat_detection/core/ | grep test
        
        echo "=== Test file lookup ==="
        echo "Looking for test audio files..."
        find . -name "*.mp3" -type f | grep -i test
        
        echo "=== Beat This Detector Test ==="
        # Test importing and creating the detector
        python -c "from beat_detection.core.factory import get_beat_detector; detector = get_beat_detector('beat_this'); print(f'Detector: {detector}, has detect_beats: {hasattr(detector, \"detect_beats\")}'); print(f'Detector dir: {dir(detector)}')"
        
        # Find and test with first mp3 file
        TEST_MP3=$(find . -name "*.mp3" -type f | head -n 1)
        if [ -n "$TEST_MP3" ]; then
          echo "=== Testing detector with $TEST_MP3 ==="
          python -c "from beat_detection.core.factory import get_beat_detector; detector = get_beat_detector('beat_this'); result = detector.detect_beats('$TEST_MP3'); print(f'Result type: {type(result)}, has timestamps: {hasattr(result, \"timestamps\")}'); print(f'Timestamps shape: {result.timestamps.shape if hasattr(result, \"timestamps\") else \"N/A\"}')" || echo "ERROR: Failed to run detector with test file"
        fi
        
        echo "=== Looking at the test file ==="
        cat tests/test_beat_this.py | head -n 60
        
        echo "=== Looking at beat_this_detector implementation ==="
        cat beat_detection/core/beat_this_detector.py | head -n 40
        
        echo "=== Examining beat_this module ==="
        python -c "import beat_this; print(f'beat_this.__file__: {beat_this.__file__}'); print(f'beat_this contents: {dir(beat_this)}')" || echo "ERROR: Failed to examine beat_this module"
        
        echo "=== Examining sys.path ==="
        python -c "import sys; print(f'sys.path: {sys.path}')"
        
        echo "=== Running dedicated diagnostic test ==="
        python -m pytest tests/test_beat_this_diagnostic.py -v -s --override-ini="addopts="
        
    - name: Run tests
      run: |
        source .venv/bin/activate
        # Run all tests with more verbosity
        pytest -v --override-ini="addopts=" -xvs

    - name: Tag successful main branch builds
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        TAG_NAME="tests-passed-$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME 